version: '3'

services:
  server:
    container_name: NODEJS_SERVER_MEDIUM
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '4000:4000'

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_DELAY=1.5
      - RELOAD_CONTAINER=<NODEJS_SERVER_MEDIUM>
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./:/node-app
      - ./node_modules:/node-app/node_modules

  db:
    image: 'mongo'
    container_name: MONGODB_MEDIUM
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
